name: ionic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: 
          npm install -g @ionic/cli
          npm install
      - name: Build Application
        run: 
          npm run build
      - name: Run Tests
        run: 
          npm run test:unit
      - name: Run Linter
        run: 
          npm run lint
